package com.lloydsbanking.salsa.eligibility.client.wz;

import lib_sim_salesprocessmanagement.ia_determineeligiblecustomerinstruction.*;
import lib_sim_salesprocessmanagement.messages.DetermineEligibleCustomerInstructionsRequest;
import lib_sim_salesprocessmanagement.messages.DetermineEligibleCustomerInstructionsResponse;

public interface EligibilityClient {
    DetermineEligibleCustomerInstructionsResponse determineEligibleInstructions(DetermineEligibleCustomerInstructionsRequest deciRequest) throws DetermineEligibleCustomerInstructionsInternalServiceErrorMsg, DetermineEligibleCustomerInstructionsExternalServiceErrorMsg, DetermineEligibleCustomerInstructionsDataNotAvailableErrorMsg, DetermineEligibleCustomerInstructionsResourceNotAvailableErrorMsg, DetermineEligibleCustomerInstructionsExternalBusinessErrorMsg;

    public void setSoapMessagesLogFilename(final String soapMessagesLogFilename);

}
