package com.lloydsbanking.salsa.offer.apply.errorcode;


public enum ConditionCodes {

    ERROR_CONDITION_OCCURRED_IN_COMMAND(1),
    RDATT_CONDITION_OCCURRED_IN_COMMAND(2),
    WRBRK_CONDITION_OCCURRED_IN_COMMAND(3),
    EOF_CONDITION_OCCURRED_IN_COMMAND(4),
    EODS_CONDITION_OCCURRED_IN_COMMAND(5),
    EOC_CONDITION_OCCURRED_IN_COMMAND(6),
    INBFMH_CONDITION_OCCURRED_IN_COMMAND(7),
    ENDINPT_CONDITION_OCCURRED_IN_COMMAND(8),
    NONVAL_CONDITION_OCCURRED_IN_COMMAND(9),
    NOSTART_CONDITION_OCCURRED_IN_COMMAND(10),
    TERMIDERR_CONDITION_OCCURRED_IN_COMMAND(11),
    FILENOTFOUND_CONDITION_OCCURRED_IN_COMMAND(12),
    NOTFND_CONDITION_OCCURRED_IN_COMMAND(13),
    DUPREC_CONDITION_OCCURRED_IN_COMMAND(14),
    DUPKEY_CONDITION_OCCURRED_IN_COMMAND(15),
    INVREQ_CONDITION_OCCURRED_IN_COMMAND(16),
    IOERR_CONDITION_OCCURRED_IN_COMMAND(17),
    NOSPACE_CONDITION_OCCURRED_IN_COMMAND(18),
    NOTOPEN_CONDITION_OCCURRED_IN_COMMAND(19),
    ENDFILE_CONDITION_OCCURRED_IN_COMMAND(20),

    ILLOGIC_CONDITION_OCCURRED_IN_COMMAND(21),
    LENGERR_CONDITION_OCCURRED_IN_COMMAND(22),
    QZERO_CONDITION_OCCURRED_IN_COMMAND(23),
    SIGNAL_CONDITION_OCCURRED_IN_COMMAND(24),
    QBUSY_CONDITION_OCCURRED_IN_COMMAND(25),
    ITEMERR_CONDITION_OCCURRED_IN_COMMAND(26),
    PGMIDERR_CONDITION_OCCURRED_IN_COMMAND(27),
    TRANSIDERR_CONDITION_OCCURRED_IN_COMMAND(28),
    ENDDATA_CONDITION_OCCURRED_IN_COMMAND(29),
    EXPIRED_CONDITION_OCCURRED_IN_COMMAND(31),
    RETPAGE_CONDITION_OCCURRED_IN_COMMAND(32),
    RTEFAIL_CONDITION_OCCURRED_IN_COMMAND(33),
    RTESOME_CONDITION_OCCURRED_IN_COMMAND(34),
    TSIOERR_CONDITION_OCCURRED_IN_COMMAND(35),
    MAPFAIL_CONDITION_OCCURRED_IN_COMMAND(36),
    INVERRTERM_CONDITION_OCCURRED_IN_COMMAND(37),
    INVMPSZ_CONDITION_OCCURRED_IN_COMMAND(38),
    IGREQID_CONDITION_OCCURRED_IN_COMMAND(39),
    OVERFLOW_CONDITION_OCCURRED_IN_COMMAND(40),
    INVLDC_CONDITION_OCCURRED_IN_COMMAND(41),
    NOSTG_CONDITION_OCCURRED_IN_COMMAND(42),
    JIDERR_CONDITION_OCCURRED_IN_COMMAND(43),
    QIDERR_CONDITION_OCCURRED_IN_COMMAND(44),
    NOJBUFSP_CONDITION_OCCURRED_IN_COMMAND(45),
    DSSTAT_CONDITION_OCCURRED_IN_COMMAND(46),
    SELNERR_CONDITION_OCCURRED_IN_COMMAND(47),
    FUNCERR_CONDITION_OCCURRED_IN_COMMAND(48),
    UNEXPIN_CONDITION_OCCURRED_IN_COMMAND(49),
    NOPASSBKRD_CONDITION_OCCURRED_IN_COMMAND(50),
    NOPASSBKWR_CONDITION_OCCURRED_IN_COMMAND(51),
    UNDEFINED_CONDITION_52(52),
    SYSIDERR_CONDITION_OCCURRED_IN_COMMAND(53),
    ISCINVREQ_CONDITION_OCCURRED_IN_COMMAND(54),

    SESSIONERR_CONDITION_OCCURRED_IN_COMMAND(58),
    SYSBUSY_CONDITION_OCCURRED_IN_COMMAND(59),
    SESSBUSY_CONDITION_OCCURRED_IN_COMMAND(60),
    NOTALLOC_CONDITION_OCCURRED_IN_COMMAND(61),
    CBIDERR_CONDITION_OCCURRED_IN_COMMAND(62),
    INVEXITREQ_CONDITION_OCCURRED_IN_COMMAND(63),
    INVPARTNSET_CONDITION_OCCURRED_IN_COMMAND(64),
    INVPARTN_CONDITION_OCCURRED_IN_COMMAND(65),

    NOTAUTH_CONDITION_OCCURRED_IN_COMMAND(70),
    SUPPRESSED_CONDITION_OCCURRED_IN_COMMAND(72),
    NOSPOOL_CONDITION_OCCURRED_IN_COMMAND(80),
    TERMERR_CONDITION_OCCURRED_IN_COMMAND(81),
    ROLLEDBACK_CONDITION_OCCURRED_IN_COMMAND(82),
    UNDEFINED_CONDITION_83(83),
    DISABLED_CONDITION_OCCURRED_IN_COMMAND(84),
    ALLOCERR_CONDITION_OCCURRED_IN_COMMAND(85),
    STRELERR_CONDITION_OCCURRED_IN_COMMAND(86),
    OPENERR_CONDITION_OCCURRED_IN_COMMAND(87),
    SPOLBUSY_CONDITION_OCCURRED_IN_COMMAND(88),
    SPOLERR_CONDITION_OCCURRED_IN_COMMAND(89),
    NODEIDERR_CONDITION_OCCURRED_IN_COMMAND(90),
    TASKIDERR_CONDITION_OCCURRED_IN_COMMAND(91),
    TCIDERR_CONDITION_OCCURRED_IN_COMMAND(92),
    DSNNOTFOUND_CONDITION_OCCURRED_IN_COMMAND(93),
    LOADING_CONDITION_OCCURRED_IN_COMMAND(94),
    MODELIDERR_CONDITION_OCCURRED_IN_COMMAND(95),
    OUTDESCERR_CONDITION_OCCURRED_IN_COMMAND(96),
    PARTNERIDERR_CONDITION_OCCURRED_IN_COMMAND(97),
    PROFILEIDERR_CONDITION_OCCURRED_IN_COMMAND(98),
    NETNAMEIDERR_CONDITION_OCCURRED_IN_COMMAND(99);

    private final int errorCode;

    ConditionCodes(int errorCode) {
        this.errorCode = errorCode;
    }

    public int getErrorCode() {
        return this.errorCode;
    }

}
