package com.lloydsbanking.salsa.offer.apply.errorcode;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class RetrieveCreditScoreErrorMap {

    private static final Map<Integer, String> F205_ERROR_MAP;

    private static final String INTERNAL_SERVICE_ERROR = "Internal Service Error";
    private static final String EXTERNAL_BUSINESS_ERROR = "External Business Error";
    private static final String EXTERNAL_SERVICE_ERROR = "External Service Error";


    public String getAsmErrorCode(Integer i) {
        return F205_ERROR_MAP.get(i);
    }

    static {
        Map<Integer, String> f205ErrorMap = new HashMap<>();

        f205ErrorMap.put(AsmErrorCodes.INVALID_DATE_PASSED_TO_DATE_HANDLER.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_USERIDENTIFIER.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_USERIDENTIFIERTYPECODE.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_CHANNELOUTLETIDENTIFIER.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATOR_DATA_ITEM_NOT_POPULATED_CHANNELOUTLETTYPECODE.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_APPLICATIONSOURCECODE.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_CREDITSCORESOURCESYSTEMCODE.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.AT_LEAST_ONE_SET_OF_PERSONALDETAILS_MUST_BE_SUPPLIED.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_FIRSTFORENAME.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_SURNAME.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_EXTERNALSYSTEMIDENTIFIER.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_EXTERNALPARTYIDENTIFIERTEXT.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_PARTYBUSNSSRLTNSPCD.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_APPLCNTADDRSSCOUNT.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_FORMATTEDADDRESSINDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_UNFORMATTEDADDRESSINDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_BUILDINGNAME_OR_BUILDINGNUMBER.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_POSTCODE.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_ADDRESSFIRSTLINETEXT.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_DATEOFBIRTH.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);

        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_IN_OTHER_BANK_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_NUMBER_OF_MONTHS_IN_OTHER_BANK_ASSOCIATION_DURATION.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_OF_BUSINESS_TELEPHONE_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_CUSTOMER_LENDING_PRIORITY_CODE.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_COMPANY_GROUP_CODE.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_IN_MANDATED_SALARY_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_IN_LTSB_MORTGAGE_HELD_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_OF_IN_STORE_CARD_HELD_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_IN_CHARGE_CARD_HELD_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_IN_PENSIONABLE_EMPLOYMENT_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_IN_SECONDARY_ACCOUNT_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_IN_NEW_PARTY_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);

        f205ErrorMap.put(AsmErrorCodes.SQL_ERROR_OCCURED_ON_FUNCTION.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_OF_INPUT.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_UK_RESIDENCY_START_DATE.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);

        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_EMPLOYMENT_STATUS_CODE.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_CREDIT_SCORE_REQUEST_NUMBER.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_PRODUCT_IDENTIFIER.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.MANDATORY_DATA_ITEM_NOT_POPULATED_ADDRESS_RESIDENCE_DURATION.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_DATE_OF_BIRTH.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_OF_IN_PARTY_STAFF_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_OF_IN_HOME_TELEPHONE_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_NUMBER_OF_MONTHS_IN_BANKERS_ASSOCIATION_DURATION.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_NUMBER_OF_MONTHS_IN_CURRENT_EMPLOYMENT_DURATION.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_IN_LTSB_CREDIT_CARD_HELD_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_IN_INCOME_EXPENDITURE_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_IN_ADDRESS_TARGETING_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_IN_ADDRESS_CORRECTION_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_IN_CVRM_EMPLOYMENT_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_IN_CVRM_REL_EMPLOYMENT_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_IN_OTHER_BANK_CURRENT_ACCOUNT_IND.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_IN_OTHER_BANK_CHEQUE_CREDIT_IND.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_IN_OTHER_BANK_DEPOSIT_ACCOUNT_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_IN_OTHER_BANK_LOAN_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_IN_OTHER_BANK_DEBIT_CREDIT_INDICATOR.getAsmErrorCode(), INTERNAL_SERVICE_ERROR);

        f205ErrorMap.put(AsmErrorCodes.THE_NUMBER_OF_APPLICANTS_EXCEEDS_THE_CURRENT_SYSTEM_LIMIT_OF_5.getAsmErrorCode(), EXTERNAL_BUSINESS_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_OF_IN_FORMATTED_ADDRESS_INDICATOR.getAsmErrorCode(), EXTERNAL_BUSINESS_ERROR);
        f205ErrorMap.put(AsmErrorCodes.INVALID_VALUE_OF_IN_UNFORMATTED_ADDRESS_INDICATOR.getAsmErrorCode(), EXTERNAL_BUSINESS_ERROR);
        f205ErrorMap.put(AsmErrorCodes.ONLY_A_FORMATTED_OR_UNFORMATTED_ADDRESS_MUST_BE_SUPPLIED_NOT_BOTH.getAsmErrorCode(), EXTERNAL_BUSINESS_ERROR);
        f205ErrorMap.put(AsmErrorCodes.FUTURE_DATE_NOT_VALID_FOR_DATE_OF_BIRTH.getAsmErrorCode(), EXTERNAL_BUSINESS_ERROR);
        f205ErrorMap.put(AsmErrorCodes.CURRENCY_CODE_MUST_BE_POUNDS_STERLING_GBP.getAsmErrorCode(), EXTERNAL_BUSINESS_ERROR);
        f205ErrorMap.put(AsmErrorCodes.THE_NUMBER_OF_ADDRESSES_EXCEEDS_THE_SYSTEM_MAXIMUM_OF_4.getAsmErrorCode(), EXTERNAL_BUSINESS_ERROR);
        f205ErrorMap.put(AsmErrorCodes.AT_LEAST_ONE_ADDRESS_MUST_BE_SUPPLIED_EITHER_FORMATTED_OR_UNFORMATTED.getAsmErrorCode(), EXTERNAL_BUSINESS_ERROR);

        f205ErrorMap.put(AsmErrorCodes.DUPLICATE_EXTERNAL_SYSTEM_ID_FOUND_FOR_APPLICANT.getAsmErrorCode(), EXTERNAL_BUSINESS_ERROR);

        f205ErrorMap.put(AsmErrorCodes.CURSOR_ON_MODULE.getAsmErrorCode(), EXTERNAL_BUSINESS_ERROR);
        f205ErrorMap.put(AsmErrorCodes.CALL_TO_MODULE_FAILED_WITH_IWS_RETURN_CODE.getAsmErrorCode(), EXTERNAL_SERVICE_ERROR);

        F205_ERROR_MAP = Collections.unmodifiableMap(f205ErrorMap);
    }
}
