package com.lloydsbanking.salsa.activate.constants;

public enum CommunicationKeysEnum {

    ARRANGEMENT_ID("IB.Product.CC.AppRefNum"),
    CUSTOMER_TITLE("IB.Customer.Title"),
    CUSTOMER_LASTNAME("IB.Customer.LastName"),
    CUSTOMER_FIRSTNAME("IB.Customer.FirstName"),
    CUSTOMER_MIDDLENAMES("IB.Customer.MiddleNames"),
    PARENT_TITLE("IB.Customer.Title1"),
    PARENT_LASTNAME("IB.Customer.LastName1"),
    PARENT_FIRSTNAME("IB.Customer.FirstName1"),
    CUSTOMER_USERNAME("IB.Customer.IBUserName"),
    PRODUCT_PCA_NAME("IB.Product.PCA.ProductName"),
    PRODUCT_PCA_ACCOUNT_NUMBER("IB.Product.PCA.AccountNumber"),
    PRODUCT_PCA_SORT_CODE("IB.Product.PCA.SortCode"),
    PRODUCT_PCA_APPREFNUM("IB.Product.PCA.AppRefNum"),
    PRODUCT_PCA_OD_AMOUNT("IB.Product.PCA.ODAmount"),
    PRODUCT_PCA_OD_INTEREST_FREE_AMOUNT("IB.Product.PCA.ODInterestFreeAmount"),
    PRODUCT_PCA_COMMON("IB.Product.PCA."),
    PRODUCT_SA_NAME("IB.Product.SA.ProductName"),
    PRODUCT_SA_MASKED_ACCOUNT_NUMBER("IB.Product.SA.AccountNumerMasked"),
    PRODUCT_SA_SORT_CODE("IB.Product.SA.SortCode"),
    PRODUCT_SA_FUNDING_DAYS("IB.Product.SA.FundingDays"),
    PARENT_PRODUCT_MASKED_POSTCODE("IB.Customer.Addr.PostCodeMasked1"),
    PRODUCT_POSTCODE("IB.Customer.Addr.PostCode"),
    PRODUCT_CC_NAME("IB.Product.CCName"),
    PRODUCT_LOAN_NAME("IB.Product.Loan.ProductName"),
    PRODUCT_LOAN_REMINDER_DATE("IB.Product.Loan.ReminderDate"),
    FA_EXPIRY_DATE("IB.Product.ExpiryDate"),
    PRODUCT_MNEMONIC("IB.Product.Mnemonic"),
    PRODUCT_MASKED_ACCOUNT_NUMBER("IB.Product.AccountNumberMasked"),
    PRODUCT_MASKED_POSTCODE("IB.Customer.Addr.PostCodeMasked"),
    PRODUCT_SA_ACCOUNT_NUMBER("IB.Product.SA.AccountNumber"),
    PRODUCT_NAME("PRODUCT_NAME"),
    BUILDING_NUMBER("IB.Customer.Addr.BuildingNumber"),
    BUILDING_NAME("IB.Customer.Addr.BuildingName"),
    SUB_BUILDING_NAME("IB.Customer.Addr.SubBuildName"),
    STREET("IB.Customer.Addr.Street"),
    CITY("IB.Customer.Addr.City"),
    DISTRICT("IB.Customer.Addr.District"),
    COUNTRY("IB.Customer.Addr.Country"),
    COUNTY("IB.Customer.Addr.County"),
    ADDRESS_LINE("IB.Customer.Addr.AddrLn"),
    ADDRESS_LINE_1("IB.Customer.Addr.AddrLn1"),
    ADDRESS_LINE_2("IB.Customer.Addr.AddrLn2"),
    ADDRESS_LINE_3("IB.Customer.Addr.AddrLn3"),
    ADDRESS_LINE_4("IB.Customer.Addr.AddrLn4"),
    ADDRESS_LINE_5("IB.Customer.Addr.AddrLn5"),
    ADDRESS_LINE_6("IB.Customer.Addr.AddrLn6"),
    ADDRESS_LINE_7("IB.Customer.Addr.AddrLn7"),
    INTERMEDIARY_NAME("IB.Product.CC.IntermediaryName"),
    INTERMEDIARY_ADDRESS_LINE_1("IB.Product.CC.IntermediaryAddrLn1"),
    INTERMEDIARY_ADDRESS_LINE_2("IB.Product.CC.IntermediaryAddrLn2"),
    INTERMEDIARY_ADDRESS_LINE_3("IB.Product.CC.IntermediaryAddrLn3"),
    CCA_SIGNED_DATE("IB.Product.CC.CCASignedDate"),
    CC_PRODUCT_NAME("IB.Product.CC.ProductName"),
    BTRATE("IB.Product.CC.BTRate"),
    BTTIME("IB.Product.CC.BTTime"),
    APR("IB.Product.CC.APR"),
    BTFEEPER("IB.Product.CC.BTFeePer"),
    ANNUALFEE("IB.Product.CC.AnnualFee"),
    REPPURVAL("IB.Product.CC.RepPurVal"),
    TCC("IB.Product.CC.TCC"),
    PURAPR("IB.Product.CC.PurAPR"),
    PURMPR("IB.Product.CC.PurMPR"),
    CASHAPR("IB.Product.CC.CashAPR"),
    CASHMPR("IB.Product.CC.CashMPR"),
    BTAPR("IB.Product.CC.BTAPR"),
    BTMPR("IB.Product.CC.BTMPR"),
    LATEFEE("IB.Product.CC.LateFee"),
    OVLMTFEE("IB.Product.CC.OvLmtFee"),
    NSFFEE("IB.Product.CC.NSFFee"),
    CADVFEEPER("IB.Product.CC.CAdvFeePer"),
    CADVFEEMIN("IB.Product.CC.CAdvFeeMin"),
    BTFEEMIN("IB.Product.CC.BTFeeMin"),
    DUEDAY("IB.Product.CC.DueDay"),
    GRACEDAY("IB.Product.CC.GraceDay"),
    CSLMTPER("IB.Product.CC.CsLmtPer"),
    INTPURRATE("IB.Product.CC.IntPurRate"),
    INTPURPRD("IB.Product.CC.IntPurPrd"),
    INTPURFEE("IB.Product.CC.IntPurFee"),
    INTCSHRATE("IB.Product.CC.IntCshRate"),
    INTCSHPRD("IB.Product.CC.IntCshPrd"),
    ICAFEE("IB.Product.CC.ICAFee"),
    LBE("IB.Product.CC.LBE"),
    PRMBTRATE("IB.Product.CC.PrmBTRate"),
    PRMBTPRD("IB.Product.CC.PrmBTPrd"),
    PRBTFEE("IB.Product.CC.PrBTFee"),
    PAYRECFEE("IB.Product.CC.PayRecFee"),
    COPYTXNFEE("IB.Product.CC.CopyTxnFee"),
    COPYSTMTFEE("IB.Product.CC.CopyStmtFee"),
    FXCOMM("IB.Product.CC.FXComm"),
    CHQFEEMIN("IB.Product.CC.ChqFeeMin"),
    CHQFEEPER("IB.Product.CC.ChqFeePer"),
    RETURNFEE("IB.Product.CC.ReturnFee"),
    TAP("IB.Product.CC.TAP"),
    NW_AC_CAM("IB.Product.CC.NW_AC_CAM"),
    BT_OFF_1("IB.Product.CC.BT_OFF_1"),
    RES_ID("IB.Product.CC.RES_ID"),
    MUL_SC_2("IB.Product.CC.MUL_SC_2"),
    MUL_SC_1("IB.Product.CC.MUL_SC_1"),
    ACC_LOGO("IB.Product.CC.ACC_LOGO"),
    DEF_PRM_PL("IB.Product.CC.DEF_PRM_PL"),
    GENCNDN("IB.Product.CC.GENCndn"),
    DEF_RTL_PL("IB.Product.CC.DEF_RTL_PL"),
    MAC("IB.Product.CC.MAC"),
    ACC_ORG("IB.Product.CC.ACC_ORG"),
    ISS_ID("IB.Product.CC.ISS_ID"),
    DEF_CH_PL("IB.Product.CC.DEF_CH_PL"),
    ACC_BIN("IB.Product.CC.ACC_BIN"),
    MNEMONIC("IB.Product.CC.Mnemonic"),
    PYMTDUENTPRD("IB.Product.CC.PymtDueNtPrd"),
    NUMBER_OF_DAYS("NUMBER_OF_DAYS"),
    PRODUCT_CC_BT_CARD_NUMBER("IB.Product.CC.BTCreditCardNumber"),
    PRODUCT_CC_BT_STATUS("IB.Product.CC.BTStatus"),
    PRODUCT_CC_BT_AMOUNT("IB.Product.CC.BTAmount"),
    PRODUCT_CC_BT_CONTENT_ID("IB.Product.CC.BTRowDetails"),
    PRODUCT_CC_TOTAL_BT_AMOUNT("IB.Product.CC.TotalBTAmount"),
    SARATECASH("IB.Product.CC.SARateCash"),
    SARATEPURCHASE("IB.Product.CC.SARatePurchase"),
    SARATEBT("IB.Product.CC.SARateBT"),
    SARATEDEFAULT("IB.Product.CC.SARateDefault");

    private final String key;

    CommunicationKeysEnum(String key) {
        this.key = key;
    }

    public String getKey() {
        return this.key;
    }

}