package com.lloydsbanking.salsa.activate.constants;

public enum EmailTemplateEnum {

    WELCOME_EMAIL("WELCOME_MSG"),
    BANK_DECLINE_EMAIL("DECLINE_BANK_MSG"),
    DUPLICATE_DECLINE_EMAIL("DECLINE_DPLICT_MSG"),
    BUREAU_DECLINE_EMAIL("DECLINE_BUREAU_MSG"),
    REFER_TO_BRANCH_EMAIL("REFERTOBRANCH_MSG"),
    EIDNV_REMINDER_EMAIL("EIDNV_REMINDER_MSG"),
    EIDNV_REFERAL_DECLINE_EMAIL("EIDNV_DECLINE_MSG"),
    APPLICATION_ABANDENED_EMAIL("APPL_ABANDND_MSG"),
    EIDNV_REFERAL_CANCEL_EMAIL("EIDNV_CANCEL_MSG"),
    SA_WELCOME_EMAIL("SA_WELCOME_MSG"),
    SA_WELCOME_LINK("SA_WELCOME_NOM_MSG"),
    SA_BANK_DECLINE_EMAIL("SA_DECLINE_BANK_MSG"),
    SA_REFER_TO_BRANCH_EMAIL("SA_REFERTOBRANCH_MSG"),
    SA_EIDNV_REMINDER_EMAIL("SA_EIDNV_REMINDER_MSG"),
    SA_EIDNV_DECLINE_EMAIL("SA_EIDNV_DECLINE_MSG"),
    SA_APPLICATION_ABANDENED_EMAIL("SA_APPL_ABANDONED_MSG"),
    SA_FUNDING_REM_EMAIL("SA_FUNDING_REM_MSG"),
    SA_FUNDING_REMD_EMAIL("SA_FUNDING_REMD_MSG"),
    SA_EIDNV_CANCEL_EMAIL("SA_EIDNV_CANCEL_MSG"),
    CA_WELCOME_MSG("CA_WELCOME_MSG"),
    CA_REFERTOBRANCH_MSG("CA_REFERTOBRANCH_MSG"),
    CA_ONLINETOOFFLINE_MSG("CA_ONLINETOOFFLINE_MSG"),
    CA_EIDNV_REMINDER_MSG("CA_EIDNV_REMINDER_MSG"),
    CA_EIDNV_DECLINE_MSG("CA_EIDNV_DECLINE_MSG"),
    CA_APPL_ABANDONED_MSG("CA_APPL_ABANDONED_MSG"),
    CA_BENEFITS_MSG("CA_BENEFITS_MSG"),
    CA_WELCOME_MSG_PDF("CA_WELCOME_MSG_PDF"),
    CA_EIDNV_CANCEL_MSG("CA_EIDNV_CANCEL_MSG"),
    CAR_FINANCE_DD_REMINDER_EMAIL("CAR_FINANCE_DD_REMINDER_EMAIL"),
    IB_STP_REGISTRATION_SUCCESS_MAIL("IB_STP_REGISTRATION_SUCCESS_MAIL"),
    IB_STP_LITE_REGISTRATION_SUCCESS_MAIL("IB_STP_LITE_REGISTRATION_SUCCESS_MAIL"),
    LOANS_COMPLETE_PRE_CCA_MSG("LOANS_COMPLETE_PRE_CCA_MSG"),
    LOANS_DRAWDOWN_POST_CCA_MSG("LOANS_DRAWDOWN_POST_CCA_MSG"),
    LOANS_REMINDER_POST_CCA_MSG("LOANS_REMINDER_POST_CCA_MSG"),
    LOANS_REMINDER_PRE_CCA_MSG("LOANS_REMINDER_PRE_CCA_MSG"),
    LRA_DECLINE_MSG("LOANS_LRA_DECLINE_MSG"),
    LRA_ACCEPT_MSG("LOANS_LRA_ACCEPT_MSG"),
    SA_ONLINE_TO_OFFLINE_NOTIFICATION("SA_ONLINETOOFFLINE_MSG"),
    ONLINE_TO_OFFLINE_NOTIFICATION("ONLINETOOFFLINE_MSG"),
    CA_ONLINE_TO_OFFLINE_NOTIFICATION("CA_ONLINETOOFFLINE_MSG"),
    SA_DUPLICATE_DECLINE_EMAIL("SA_DECLINE_DPLICT_MSG"),
    SA_BUREAU_DECLINE_EMAIL("SA_DECLINE_BUREAU_MSG"),
    CA_DECLINE_BANK_MSG("CA_DECLINE_BANK_MSG"),
    CA_DECLINE_DPLICT_MSG("CA_DECLINE_DPLICT_MSG"),
    CA_DECLINE_BUREAU_MSG("CA_DECLINE_BUREAU_MSG"),
    BT_FULFILLED_EMAIL("BT_FULFILLED_MSG"),
    BT_PARTIALLY_FULFILLED_EMAIL("BT_PRTLY_FULFLD_MSG"),
    BT_FAILED_EMAIL("BT_FAILED_MSG");

    private final String template;

    EmailTemplateEnum(String template) {
        this.template = template;
    }

    public String getTemplate() {
        return this.template;
    }
}
