package com.lloydsbanking.salsa.apacc.service.fulfil.rules;

public enum F251ErrorCodes {
    OFFER_ADD_SERVICE_FAILED_TO_ADD_OFFER_AT_OCCURANCE_4(41159),
    OFFER_ADD_SERVICE_FAILED_TO_ADD_OFFER_AT_OCCURANCE_3(41158),
    OFFER_ADD_SERVICE_FAILED_TO_ADD_OFFER_AT_OCCURANCE_2(41157),
    OFFER_ADD_SERVICE_FAILED_TO_ADD_OFFER_AT_OCCURANCE_1(41156),
    CANNOT_CONTINUE_FURTHER_PROCESSING_AS_MAX_ERROR_COUNT_REACHEDF(41154),
    OFFER_ADD_SERVICE_FAILED_TO_ADD_OFFER_AT_OCCURANCE_10(41155),
    ORG_IN_ADD_PENDING_STATUS(41011),
    ORG_RECORD_STATUS_INCOMPELETE_OR_TO_BE_PURGED(41150),
    GETMAIN_FOR_OFFER_ADD_INPUT_AREA_FAILED(41152),
    FILE_ERROR_WHILE_READING_OFFER_ORG_RECORD(41151),
    EFFECTIVE_DATE_INVALID(41761),
    OFFER_ENROLLMENT_ALREADY_ON_FILE(41762),
    INVALID_ENROLLMENT_ACTION_FOR_ADD_ON_PRODUCT_OFFER_TYPE(41243),
    EFF_DATE_INVALID_MUST_BE_GREATER_THAN_NEXT_PROCESSING_DATE(41239),
    EFFECTIVE_DATE_INVALID_VALUE_ONLY_ALLOWED_FOR_ADD_ON_PRODUCT(41248),
    ENROLL_ACTION_MUST_BE_NUMERIC(41235),
    INVALID_USER(41166),
    SERVICE_INPUT_LENGTH_ERROR(41013),
    INVALID_ACCOUNT_ACCOUNT_NOT_NUMERIC(41004),
    INVALID_ORG_ORG_NOT_NUMERIC(41007),
    GETMAIN_FOR_OFFER_ADD_OUPUT_AREA_FAILED(41153),
    OFFER_DEFINITION_RECORD_NOT_FOUND(41242),
    FILE_TABLE_NOT_FOUND_ON_SMFT_FILE(41167),
    OFFER_ID_MUST_BE_PRESENT_TO_ADD_OFFER(41149),
    SYSTEM_IN_AFTER_HOURS_STATE_PLEASE_SUBMIT_LATER(41117),
    USER_DOES_NOT_HAVE_ACCESS_TO_THIS_ORG(41003),
    GET_MAIN_FAILED_FOR_THE_INPUT_COPYBOOK(41165),
    OFFER_ADD_SERVICE_FAILED_TO_ADD_OFFER_AT_OCCURANCE_9(41164),
    OFFER_ADD_SERVICE_FAILED_TO_ADD_OFFER_AT_OCCURANCE_8(41163),
    OFFER_ADD_SERVICE_FAILED_TO_ADD_OFFER_AT_OCCURANCE_7(41162),
    OFFER_ADD_SERVICE_FAILED_TO_ADD_OFFER_AT_OCCURANCE_6(41161),
    OFFER_ADD_SERVICE_FAILED_TO_ADD_OFFER_AT_OCCURANCE_5(41160);


    private int errorCode;

    F251ErrorCodes(int errorCode) {
        this.errorCode = errorCode;
    }

    public int getErrorCode() {
        return errorCode;
    }

    public static boolean isErrorForF251(Integer errorCode) {
        for (F251ErrorCodes f251ErrorCodes : F251ErrorCodes.values()) {
            if (f251ErrorCodes.errorCode == errorCode) {
                return Boolean.TRUE;
            }
        }
        return Boolean.FALSE;
    }

}
