package com.lloydsbanking.salsa.aps.client;


import lib_sim_productsalesreferencedatamanager.id_determineproducteligibilitytype.AdministerProductSelectionDataNotAvailableErrorMsg;
import lib_sim_productsalesreferencedatamanager.id_determineproducteligibilitytype.AdministerProductSelectionInternalServiceErrorMsg;
import lib_sim_productsalesreferencedatamanager.id_determineproducteligibilitytype.AdministerProductSelectionResourceNotAvailableErrorMsg;
import lib_sim_productsalesreferencedatamanager.messages.AdministerProductSelectionRequest;
import lib_sim_productsalesreferencedatamanager.messages.AdministerProductSelectionResponse;

public interface ApsClient {

    AdministerProductSelectionResponse administerProductSelection (AdministerProductSelectionRequest request) throws AdministerProductSelectionDataNotAvailableErrorMsg, AdministerProductSelectionInternalServiceErrorMsg, AdministerProductSelectionResourceNotAvailableErrorMsg;

    public void setSoapMessagesLogFilename(final String soapMessagesLogFilename);
}
