package com.lloydsbanking.salsa.ppae.service.constant;


public interface AppStatusConstant {

    String AWAITING_RESCORE = "AWAITING_RESCORE";
    String AWAITING_REFERRAL = "AWAITING_REFERRAL";
    String AWAITING_MANUAL_ID_V = "AWAITING_MANUAL_ID_V";
    String ABANDONED = "ABANDONED";
    String AWAITING_POST_FULFILMENT_PROCESS = "AWAITING_POST_FULFILMENT_PROCESS";
    String AWAITING_FULFILMENT = "AWAITING_FULFILMENT";
    String CCA_SIGNED_CCA_PENDING = "CCA_SIGNED_CCA_PENDING";
    String AWAITING_REFERRAL_LRA = "AWAITING_REFERRAL_LRA";
    String NEW_CAR = "NEW_CAR";

}
